/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.masil.seoulyeok.events.relay.api;

import org.masil.seoulyeok.events.relay.models.RelayRequest;
import org.masil.seoulyeok.events.relay.models.Result;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;


import javax.validation.Valid;

@javax.annotation.Generated(value = "com.trevari.oas.codegen.spring.TrevariSpringCodeGenerator")
@Validated

@RestController
public interface RelayApi {

    /**
     * POST /apis/events/relay : 특정 메세지를 목적지로 전달합니다
     * 특정 메세지를 목적지로 전달합니다
     *
     * @param relayRequest deliveryToDestination (required)
     * @return 데이터 전송 성공 code &#x3D; 0, meg: ok (status code 200)
     *         or 입력이 유효하지 않습니다 code &#x3D; -1, meg: fail (status code 400)
     *         or 시스템 오류 발생 code &#x3D; -1, meg: fail (status code 500)
     */

    @PostMapping(
        value = "/apis/events/relay",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Result> deliveryToDestination(@Valid @RequestBody RelayRequest relayRequest);

}
